# Generated by Django 4.2.3 on 2023-12-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zammyaccount",
            name="login_type",
            field=models.CharField(
                choices=[("EMAIL", "email"), ("GOOGLE", "google"), ("LINE", "line")],
                default="EMAIL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="zammyaccount",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zammyaccount",
            unique_together={("email", "login_type")},
        ),
    ]
