# Generated by Django 4.2.3 on 2023-12-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_zammyaccount_login_type_alter_zammyaccount_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zammyaccount",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="username"),
        ),
    ]
